---
name: build and push image
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: what-time-is-it
      PROJECT_ID: bux-assignment-dpakhomov
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Build image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Configure client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
      - name: Push image
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push europe-west4-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
    